import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "@/componant/Header";
import Feapost_left from "../public/feapost.png";
import Cat_logo from "../public/category/Icon.svg";
import Cat_logo1 from "../public/category/economy (1).svg";
import Cat_logo2 from "../public/Icon11.png";
import Cat_logo3 from "../public/category/cyborg.svg";
import People from "../public/category/photo.png";
import auther from "../public/auther/auther1.png";
import auther1 from "../public/auther/auther2.png";
import auther2 from "../public/auther/auther3.png";
import auther3 from "../public/auther/auther4.png";
import Icon1 from "../public/social_icon/LIKDIN.svg";
import Icon2 from "../public/social_icon/facebooke.svg";
import Icon3 from "../public/social_icon/instagram.svg";
import Icon4 from "../public/social_icon/twwetr.svg";
import Brand1 from "../public/social_icon/Logo 1.svg";
import Brand2 from "../public/social_icon/Logo 2.svg";
import Brand3 from "../public/social_icon/Logo 3.svg";
import Brand4 from "../public/social_icon/Logo 4.svg";
import Brand5 from "../public/social_icon/Logo 5.svg";
import People1 from "../public/category/gg.png";
import Leftaroow from "../public/category/Arrow 1.svg";
import right from "../public/category/Arrow 1 (1).svg";
import Footer from "@/componant/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <section className={styles.hero_sec}>
          <h1 className={styles.post}>
            Posted on <b>startup</b>
          </h1>
          <h2>
            Step-by-step guide to choosing<br/>
           great font pairs
          </h2>
          <h3>
            By <span>James West</span> | May 23, 2022{" "}
          </h3>
          <h4>
            Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu
            <br /> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident.
          </h4>
          <div className={styles.read_btn}>
            <button>
              <h1>Read More &gt; </h1>
            </button>
          </div>
        </section>
        <section className={styles.post_sec}>
          <div>
            <h1 className={styles.fea_head}>Featured Post</h1>
            <div className={styles.Feature_post}>
              <Image src={Feapost_left} alt="dd" />
              <p className={styles.fea_date}>By John Doe l May 23, 2022</p>
              <h1 className={styles.fea_desc}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor.
              </h1>
              <h2 className={styles.fea_small_text}>
                Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
                cupidatat non proident.
              </h2>
              <div className={styles.fea_btn}>
                <button>Read More &gt;</button>
              </div>
            </div>
          </div>

          <div className={styles.app_post}>
            <div className={styles.right_fea}>
              <h1 className={styles.left_fea}>All Posts</h1>
              <h2 className={styles.allpost}> View All</h2>
            </div>

            <div className={styles.post_cont}>
              <h1>
                By <p className={styles.pp}>John Deo</p> | Aug 23, 2021{" "}
              </h1>

              <h2>
                8 Figma design systems that you can download for free today.
              </h2>
            </div>
            <div className={styles.post_cont}>
              <h1>
                By <p className={styles.pp}>John Deo</p> | Aug 23, 2021{" "}
              </h1>
              <h2>
                8 Figma design systems that you can download for free today.
              </h2>
            </div>
            <div className={styles.post_cont}>
              <h1>
                By <p className={styles.pp}>John Deo</p> | Aug 23, 2021{" "}
              </h1>

              <h2>
                8 Figma design systems that you can download for free today.
              </h2>
            </div>
            <div className={styles.post_cont}>
              <h1>
                By <p className={styles.pp}>John Deo</p> | Aug 23, 2021{" "}
              </h1>

              <h2>
                8 Figma design systems that you can download for free today.
              </h2>
            </div>
          </div>
        </section>
        <section className={styles.third_sec}>
          <div className={styles.back_frame}>
            <div className={styles.yellow}></div>
            <div className={styles.blue}></div>
          </div>
          <div className={styles.rap_cont}>
            <div className={styles.about_cont}>
              <h1>ABOUT US</h1>
              <h2>
                We are a community of <br />
                content writers who share their learnings
              </h2>
              <h3>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </h3>
              <h4>Read More </h4>
            </div>

            <div className={styles.mission_cont}>
              <h1>Our mision</h1>
              <h2>
                Creating valuable content for
                <br /> creatives all around the world
              </h2>
              <h3>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat.
              </h3>
            </div>
          </div>
        </section>
        <section className={styles.fourth_sec}>
          <h1 className={styles.heading}>Choose A Catagory</h1>
          <div className={styles.category_rap}>
            <Link href="/Category">
              <div className={styles.category_cont}>
                <Image src={Cat_logo2} alt="jj" />
                <h2 className={styles.cot_name}>Business</h2>
                <h3 className={styles.cot_desc}>
                  Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                </h3>
              </div>
            </Link>
            <div id={styles.sohan} className={styles.category_cont}>
              <Image src={Cat_logo} alt="jj" />
              <h2 className={styles.cot_name}>Startup</h2>
              <h3 className={styles.cot_desc}>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
              </h3>
            </div>
            <div className={styles.category_cont}>
              <Image src={Cat_logo1} alt="jj" />
              <h2 className={styles.cot_name}>Economy</h2>
              <h3 className={styles.cot_desc}>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
              </h3>
            </div>
            <div className={styles.category_cont}>
              <Image src={Cat_logo3} alt="jj" />
              <h2 className={styles.cot_name}>Technology</h2>
              <h3 className={styles.cot_desc}>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
              </h3>
            </div>
          </div>
        </section>
        <section className={styles.fiveth}>
          <Link href="/Auther"></Link>
          <div className={styles.photo}>
            <Image src={People} alt="dd" />
          </div>
          <div className={styles.title}>
            <h1>Why we started </h1>
            <h2>
              It started out as a simple idea and evolved into our passion
            </h2>
            <h3>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip.
            </h3>
            <div className={styles.title_btn}>
              <h1>Discover our story</h1>{" "}
            </div>
          </div>
        </section>
        <section className={styles.sixth_sec}>
          <h1>List of Authors</h1>
          <div className={styles.all_rap}>
            {" "}
            <div className={styles.auther_rap}>
              <Link href="/Auther">
                {" "}
                <div className={styles.auther_cont}>
                  <Image className={styles.hero} src={auther3} alt="dd" />
                  <h2>Floyd Miles</h2>
                  <h3>Content Writer @Company</h3>
                  <div className={styles.social_rap}>
                    <Image src={Icon2} alt="dd" />
                    <Image src={Icon4} alt="dd" />
                    <Image src={Icon3} alt="dd" />
                    <Image src={Icon1} alt="dd" />
                  </div>
                </div>
              </Link>

              <div className={styles.auther_cont}>
                <Image className={styles.hero} src={auther1} alt="dd" />
                <h2>Dianne Russell</h2>
                <h3>Content Writer @Company</h3>
                <div className={styles.social_rap}>
                  <Image src={Icon2} alt="dd" />
                  <Image src={Icon4} alt="dd" />
                  <Image src={Icon3} alt="dd" />
                  <Image src={Icon1} alt="dd" />
                </div>
              </div>
              <div className={styles.auther_cont}>
                <Image className={styles.hero} src={auther2} alt="dd" />
                <h2>Jenny Wilson</h2>
                <h3>Content Writer @Company</h3>
                <div className={styles.social_rap}>
                  <Image src={Icon2} alt="dd" />
                  <Image src={Icon4} alt="dd" />
                  <Image src={Icon3} alt="dd" />
                  <Image src={Icon1} alt="dd" />
                </div>
              </div>
              <div className={styles.auther_cont}>
                <Image className={styles.hero} src={auther} alt="dd" />
                <h2>Leslie Alexander </h2>
                <h3>Content Writer @Company</h3>
                <div className={styles.social_rap}>
                  <Image src={Icon1} alt="dd" />
                  <Image src={Icon4} alt="dd" />
                  <Image src={Icon3} alt="dd" />
                  <Image src={Icon1} alt="dd" />
                </div>
              </div>
            </div>
          </div>

          <div className={styles.feature_cont}>
            <div className={styles.brad_scroll}>
              <div className={styles.fea_text}>
              <h1>We are</h1>
              <h2>Featured in</h2>
            </div>
            <div className={styles.all_brand}>
              <Image src={Brand1} alt="s" />
              <Image src={Brand2} alt="s" />
              <Image src={Brand3} alt="s" />
              <Image src={Brand4} alt="s" />
              <Image src={Brand5} alt="s" />
            </div></div>
            
          </div>
        </section>
        <section className={styles.people_say}>
          <div className={styles.left}>
            <h1>TESTIMONIALS</h1>
            <h2>What people say about our blog</h2>
            <h3>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor.
            </h3>
          </div>
          <div className={styles.right}>
            <h1>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </h1>
            <div className={styles.people_cont}>
              {" "}
              <div className={styles.img_cont}>
                <Image src={People1} alt="hh" />
              </div>{" "}
              <div className={styles.people_name}>
                <h1>Jonathan Vallem</h1>
                <h2>New york, USA</h2>
              </div>
              <div className={styles.switch_arrow}>
                <Image src={Leftaroow} alt="jj" /> <Image src={right} alt="h" />
              </div>{" "}
            </div>
          </div>
        </section>
        <section className={styles.joineepart}>
          <h1>Join our team to be a part of our story</h1>
          <h2>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt.
          </h2>
          <button>
            <h3>Join Now</h3>
          </button>
        </section>
        <Footer/>
      </main>
    </>
  );
}
